---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certificate-updater-sa
  namespace: certificate-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certificate-updater-rb
  namespace: certificate-updater
subjects:
  - kind: ServiceAccount
    name: certificate-updater-sa
    namespace: certificate-updater
roleRef:
  kind: ClusterRole
  name: system:controller:node-controller
  apiGroup: rbac.authorization.k8s.io